<?php

namespace BlogBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use BlogBundle\Entity\Comment;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadBlogBundleEntityComment extends Fixture implements OrderedFixtureInterface, ContainerAwareInterface {

    /**
     * @var ContainerInterface
     */
    private $container;

    public function setContainer(ContainerInterface $container = null) {
        $this->container = $container;
    }

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder() {
        return 3;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager) {
        $manager->getClassMetadata(Comment::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $em = $this->container->get('doctrine')->getEntityManager();
        $em->getConnection()->exec('ALTER TABLE comment AUTO_INCREMENT = 1');

        $item25 = new Comment();
        $this->addReference('_reference_BlogBundleEntityComment25', $item25);
        $item25->setIsValid(true);
        $item25->setContent("Une sale affaire...");
        $item25->setDate(new \DateTime("2018-01-07 23:43:26"));
        $item25->setName("Guillaume H");
        $item25->setPost($this->getReference('_reference_BlogBundleEntityPost1'));
        $item25->setUser($this->getReference('_reference_BlogBundleEntityUser1'));

        $manager->persist($item25);

        $item26 = new Comment();
        $this->addReference('_reference_BlogBundleEntityComment26', $item26);
        $item26->setIsValid(true);
        $item26->setContent("A quand les bombes en kit chez votre marchand de journaux ?");
        $item26->setDate(new \DateTime("2018-01-07 23:44:26"));
        $item26->setName("Guillaume H");
        $item26->setPost($this->getReference('_reference_BlogBundleEntityPost3'));
        $item26->setUser($this->getReference('_reference_BlogBundleEntityUser1'));

        $manager->persist($item26);

        $item27 = new Comment();
        $this->addReference('_reference_BlogBundleEntityComment27', $item27);
        $item27->setIsValid(true);
        $item27->setContent("Moi j'ai une connexion pourri");
        $item27->setDate(new \DateTime("2018-01-07 23:45:11"));
        $item27->setName("Jean-Michel");
        $item27->setPost($this->getReference('_reference_BlogBundleEntityPost1'));

        $manager->persist($item27);

        $item28 = new Comment();
        $this->addReference('_reference_BlogBundleEntityComment28', $item28);
        $item28->setContent("Il pourra toujours s'enfuir en vélo volant.");
        $item28->setDate(new \DateTime("2018-01-07 23:46:21"));
        $item28->setName("Maxime");
        $item28->setPost($this->getReference('_reference_BlogBundleEntityPost2'));

        $manager->persist($item28);

        $item29 = new Comment();
        $this->addReference('_reference_BlogBundleEntityComment29', $item29);
        $item29->setIsValid(true);
        $item29->setContent("De futurs chirurgiens !");
        $item29->setDate(new \DateTime("2018-01-07 23:47:07"));
        $item29->setName("Sarah");
        $item29->setPost($this->getReference('_reference_BlogBundleEntityPost5'));

        $manager->persist($item29);

        $item30 = new Comment();
        $this->addReference('_reference_BlogBundleEntityComment30', $item30);
        $item30->setIsValid(true);
        $item30->setContent("J'ai déjà prévu de partir !");
        $item30->setDate(new \DateTime("2018-01-07 23:47:46"));
        $item30->setName("Elon Musk");
        $item30->setPost($this->getReference('_reference_BlogBundleEntityPost7'));

        $manager->persist($item30);

        $item31 = new Comment();
        $this->addReference('_reference_BlogBundleEntityComment31', $item31);
        $item31->setContent("Du coup faut réécrire le générique.");
        $item31->setDate(new \DateTime("2018-01-07 23:48:34"));
        $item31->setName("Thomas");
        $item31->setPost($this->getReference('_reference_BlogBundleEntityPost6'));

        $manager->persist($item31);


        $manager->flush();
    }

}
