<?php

namespace BlogBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use BlogBundle\Entity\User;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadBlogBundleEntityUser extends Fixture implements OrderedFixtureInterface, ContainerAwareInterface
{

    /**
     * @var ContainerInterface
     */
    private $container;

    public function setContainer(ContainerInterface $container = null) {
        $this->container = $container;
    }

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(User::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $em = $this->container->get('doctrine')->getEntityManager();
        $em->getConnection()->exec('ALTER TABLE user AUTO_INCREMENT = 1');

        $item1 = new User();
        $this->addReference('_reference_BlogBundleEntityUser1', $item1);
        $item1->setFirstname("Guillaume");
        $item1->setLastname("HANOTEL");
        $item1->setImageName("guillaume-hanotel300x300.jpg");
        $item1->setImagePath("/assets/database_files/avatar/guillaume-hanotel300x300.jpg");
        $item1->setImageSize(96603);
        $item1->setUsername("guillaumeh");
        $item1->setUsernameCanonical("guillaumeh");
        $item1->setEmail("guillaumehanotel@orange.fr");
        $item1->setEmailCanonical("guillaumehanotel@orange.fr");
        $item1->setEnabled(true);
        $item1->setSalt("d25e6436ed5eb0927f0dc94f4ea64ba2");
        $item1->setPassword("\$2y\$13\$UnDzRFs7ROQzt8kqNf9Ot.vFQeB/bJBhX4faEM77NwNa4S5P3fC6m");
        $item1->setLastLogin(new \DateTime("2018-01-07 23:48:56"));
        $item1->setRoles(unserialize('a:1:{i:0;s:16:"ROLE_SUPER_ADMIN";}'));

        $manager->persist($item1);

    
        $manager->flush();
    }

}
