<?php

namespace BlogBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use BlogBundle\Entity\Post;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadBlogBundleEntityPost extends Fixture implements OrderedFixtureInterface, ContainerAwareInterface {

    /**
     * @var ContainerInterface
     */
    private $container;

    public function setContainer(ContainerInterface $container = null) {
        $this->container = $container;
    }

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder() {
        return 2;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager) {
        $manager->getClassMetadata(Post::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $em = $this->container->get('doctrine')->getEntityManager();
        $em->getConnection()->exec('ALTER TABLE post AUTO_INCREMENT = 1');

        $item7 = new Post();
        $this->addReference('_reference_BlogBundleEntityPost7', $item7);
        $item7->setTitle("Un trafic d’identifiants Freewifi démantelé dans une université lilloise");
        $item7->setContent("À l’origine de l’affaire, la générosité ingénue d’un étudiant de 2ème année qui accepte en octobre de confier ses identifiants familiaux à un camarade pour lui permettre de suivre un important match de Ligue 1. Malgré la promesse de ne pas partager partout ces identifiants, ceux-ci sont rapidement disséminés de façon incontrôlable. Mi-novembre, ce ne sont pas moins de 117 étudiants toutes années confondues qui utilisent sans vergogne le code d’accès – parfois pour des usages peu reluisants : visionnage de Grey’s Anatomy en streaming, jeux de rôle en ligne, vente de mobylettes sur Le Bon Coin…

Poursuivi par Free, l’étudiant s’est réfugié à l’ambassade du Paraguay

À la décharge des étudiants, le wi-fi rudimentaire disponible à l’université ne permet guère que de consulter ses e-mails, moyennant 12 minutes de chargement et uniquement au 1er étage du bâtiment. Dépassé par les événements, « l’étudiant-zéro » panique néanmoins – et à juste titre , Free chiffre l’ampleur de la fraude et le manque à gagner est chiffré à 380 000 euros.

Réfugié à l’ambassade du Paraguay depuis décembre, il invoque l’abus de confiance et devrait bientôt donner une conférence TED sur les dangers du numérique.");
        $item7->setDate(new \DateTime("2018-01-04 16:34:50"));
        $item7->setUser($this->getReference('_reference_BlogBundleEntityUser1'));

        $manager->persist($item7);

        $item6 = new Post();
        $this->addReference('_reference_BlogBundleEntityPost6', $item6);
        $item6->setTitle("Arrivé à la fin de son visa, l’acteur qui jouait E.T va être rapatrié vers sa planète d’origine");
        $item6->setContent("C’est fini pour Hollywood en ce qui concerne Zakari Sánchez. Dans ce film culte de Steven Spielberg sorti en 1982, cet acteur au talent exceptionnel jouait une créature extraterrestre recueillie par deux enfants après s’être perdue suite à l’arrivée de son vaisseau sur Terre. S’il est surtout connu pour ce rôle-ci et s’il s’était éloigné des projecteurs en développant une addiction à la cocaïne, il garde une place importante dans le coeur de tous ceux qui ont vu son film étant enfants.

Il se trouve que les extraterrestres ont beaucoup plus de mal à obtenir des green cards que les terriens. En effet, Zakari Sánchez n’a cessé de renouveler son permis de résidence, mais, sans emploi, on lui a récemment refusé une nouvelle prolongation. M. Sánchez garde néanmoins l’espoir de pouvoir rester aux Etats-Unis grâce à ses fans. En effet, ceux-ci ont lancé une campagne afin qu’il ne soit pas obligé de rentrer sur sa planète, sur laquelle sévit d’ailleurs une guerre atroce depuis des années.

Si la pétition obtient suffisamment de signatures, notre cher Zakari aura peut-être une chance de rester aux Etats-Unis, et il continuera à profiter de sa fortune dans sa maison de bord de plage à Malibu. Sinon, il essayera peut-être de demander l’asile politique à un pays européen. Heureusement, Zakari Sánchez parle parfaitement l’allemand !");
        $item6->setDate(new \DateTime("2018-01-04 16:34:26"));
        $item6->setUser($this->getReference('_reference_BlogBundleEntityUser1'));

        $manager->persist($item6);

        $item5 = new Post();
        $this->addReference('_reference_BlogBundleEntityPost5', $item5);
        $item5->setTitle("Texas : le 357 Magnum offert dans chaque Happy Meal relance le débat sur les armes à feu");
        $item5->setContent("16 heures, Mac Donald d’Austin. Justin, 10 ans, est en train de monter son 357 Magnum grâce à la petite notice fournie dans le coffret. Il pointe maintenant son arme en direction d’une voiture et tire sur une fenêtre. « Ça suffit Steven, papa est au téléphone, j’entends rien. » invective Marc. Le père se veut très rassurant « Il n’y a rien de dangereux, c’était une voiture de Mexicains. On lui a appris à faire la différence » nous confie-t-il.

Pourtant, cette nouvelle promotion ne fait pas l’unanimité parmi les habitants de la ville. Notamment pour Maggie, 92 ans « Les enfants ne devraient pas recevoir des armes dans un simple Happy Meal. C’est dangereux, ils ne savent même pas viser, ils pourraient se blesser. D’abord il faut les emmener dans un champ tirer sur des bouteilles de verre. S’ils arrivent à en dégommer 3, là, d’accord » nous confie la vieille dame.

D’autres plaintes sont venues compléter celle de Maggie. Notamment cette femme de 54 ans, qui manifeste aujourd’hui et qui a perdu son mari et ses deux enfants après qu’un enfant de 7 ans s’est servi de son arme. « Il faut absolument mettre fin à ce problème. Si on offre des armes à feu aux enfants gratuitement, les prix vont dégringoler et des fabricants vont devoir fermer boutique. Ce sont des milliers d’emplois américains qui sont en jeu » nous confie la veuve passablement remontée.");
        $item5->setDate(new \DateTime("2018-01-04 16:33:58"));
        $item5->setUser($this->getReference('_reference_BlogBundleEntityUser1'));

        $manager->persist($item5);

        $item4 = new Post();
        $this->addReference('_reference_BlogBundleEntityPost4', $item4);
        $item4->setTitle("Se tenir le menton entre le pouce et l’index n’augmenterait les capacités cognitives que de 12,5%");
        $item4->setContent("Une précédente étude déclarative faisait pourtant ressortir des résultats nettement supérieurs. Pour 85% des personnes interrogées, se tenir le menton entre le pouce et l’index « doublerait voire triplerait leurs capacités intellectuelles ». Cette croyance ancrée de longue date dans l’imaginaire populaire serait à elle seule responsable de la prise de « très mauvaises décisions » comme la conception de Windows Millemium ou, plus fréquemment, le désir de « goûter ses crottes de nez pour vérifier si c’est vraiment salé. »

Sachant travailler sur un sujet sensible, les responsables de l’étude se sont efforcés de suivre un protocole extrêmement complexe. Ainsi, pour isoler et neutraliser l’effet placebo, les scientifiques ont greffé aux participants de faux doigts en plastique afin d’identifier l’impact cognitif réel de vrais doigts apposés sur le menton. Une opération très coûteuse mais nécessaire car, « l’effet placebo joue ici à plein. Nous avons consacré beaucoup de temps et d’énergie pour trouver cette solution et je pense pouvoir affirmer sans me tromper que c’est une réussite », confie en fronçant les sourcils et en hochant la tête Gilles Pratzky, directeur de recherche au CNRS.

Se gratter la tête avec l’index augmente l’activité neuronale de 23%

« Il faut savoir que 12,5% c’est très peu. Cela peut aider à formuler une phrase complexe sans faute de grammaire mais c’est à peu près tout, ne vous attendez pas à comprendre un film de Philippe Garrel grâce à cela. » À titre de comparaison, se gratter la tête avec l’index ou se cogner la tête avec le poing augmente l’activité neuronale de 23% et 30%, un impact infiniment supérieur à celui de la lecture et de l’apprentissage scolaire, jugé négligeable par le rapport.");
        $item4->setDate(new \DateTime("2018-01-04 16:33:31"));
        $item4->setUser($this->getReference('_reference_BlogBundleEntityUser1'));

        $manager->persist($item4);

        $item3 = new Post();
        $this->addReference('_reference_BlogBundleEntityPost3', $item3);
        $item3->setTitle("Éducation nationale : faute de moyens, les élèves devront s’auto-disséquer en cours de SVT");
        $item3->setContent("« C’est regrettable, mais il faut faire avec, car les dissections restent au programme », s’alarme Marine Heurtault, professeur de SVT au collège, désolée de contraindre ses élèves à un exercice des plus difficiles : s’auto-disséquer. « Ça fait déjà 4 ans que, par manque d’argent, on dissèque avec des couteaux de cantine et du fil dentaire… là c’est la goutte d’eau qui fait déborder le vase ».

Un directeur d’école, M. Lifar, se veut moins pessimiste : « Certes, le budget est réduit pour les matières scientifiques. En revanche, le ministère offre une rallonge pour les réfectoires. Ce qui permettra par exemple à notre cantine d’enfin servir du cordon bleu contenant de la vraie viande, et non pas des résidus de cartilage animal comme c’est le cas depuis des années ».

Le ministre de l’Education, Jean-Michel Blanquer, préfère mettre en avant les avantages de ce changement de fonctionnement : « Ça permettra aux élèves de se dépasser ! Cette semaine, le meilleur élève d’une classe dans laquelle nous avons testé ce processus s’est lui-même retiré l’appendice ! C’est formidable ».");
        $item3->setDate(new \DateTime("2018-01-04 16:32:55"));
        $item3->setUser($this->getReference('_reference_BlogBundleEntityUser1'));

        $manager->persist($item3);

        $item2 = new Post();
        $this->addReference('_reference_BlogBundleEntityPost2', $item2);
        $item2->setTitle("Plusieurs scientifiques affirment que Denver ne serait pas vraiment le dernier dinosaure");
        $item2->setContent("Avec sa bonhomie naturelle et son sourire ravageur, Denver n’aurait il pas blousé tout le monde en se faisant passer pour le dernier dinosaure ? C’est en tout cas ce que semble croire une équipe de chercheurs américains. Au début de cette aventure, ces fameuses paroles qui hantent Steve et son équipe de chercheurs à l’université de Syracuse à New-York : Denver, le dernier dinosaure, c’est mon ami mais bien plus encore. « Pendant 30 ans les paléontologues s’étaient accordés sur ses paroles. Mais pour moi, quelque chose clochait dans cette histoire. »

Steve commence alors sa croisade mais rapidement il réalise que ses questions dérangent. « Les tortues sont également des dinosaures, plus vieilles que Denver en soi. Mais personne ne veut attaquer Denver car tout le monde aime Denver. Il met dans votre vie un peu plus de bonheur avec son grand sourire mielleux et ses lunettes de soleil posées nonchalamment sur ses sourcils. Personne ne peut attaquer un dinosaure aussi cool qui fait du skate et de la guitare électrique » Il est vrai que l’idole des années 90 bénéficiait jusqu’alors d’une aura le rendant quasi intouchable. En 1998, Michel Bournier, un paléontologue Français, avait également émis des doutes sur son titre de « Dernier Dinosaure » ; il mourait noyé dans un lac dans des conditions plus qu’étranges deux semaines plus tard.

Mais Steve, loin d’être intimidé, continue son enquête et grâce à l’appui de journalistes scientifiques, il réussit à faire paraître un article dans le très sérieux « Journal of Vertebrate Pelontholgy ». qui a un retentissement immédiat.

C’est un nouveau coup porté à la réputation du célèbre Dinosaure alors que les 4 adolescents californiens – Wally, Jeremy, Charlie et Mario – qui jouaient avec lui dans la série, avaient déjà défrayé la chronique en témoignant sur la face caché du géant vert au mois de mars dernier. Ils avaient notamment dénoncé son comportement odieux dans les loges, son addiction au crack, ses coups de colère sur les plateaux de tournages mais surtout son penchant pour les assistants mineurs. Une fois de plus, un portrait bien loin du plus gentil des animaux venu de la torride et ancienne jungle.");
        $item2->setDate(new \DateTime("2018-01-04 16:32:28"));
        $item2->setUser($this->getReference('_reference_BlogBundleEntityUser1'));

        $manager->persist($item2);

        $item1 = new Post();
        $this->addReference('_reference_BlogBundleEntityPost1', $item1);
        $item1->setTitle("La Terre : « Tuez-moi une bonne fois pour toutes, qu’on en finisse »");
        $item1->setContent("« Je suis juste blasée », soupire notre planète pendant qu’on extrait du pétrole de ses entrailles. « On peut pas juste me faire exploser comme dans Star Wars ? », suggère Mère Nature. « Comme ça, c’est fini et on n’en parle plus. »

La boule de roche et d’eau vieille de 4.5 milliards d’années a en effet mentionné son souhait de mettre fin à ses jours malgré sa chance énorme d’être située dans la zone habitable de son étoile. « Tuez-moi une bonne fois pour toutes, qu’on en finisse », a en effet déclaré la planète Boucles d’or depuis son domicile situé à 149,6 millions de kilomètres du Soleil.

« J’ai déjà vécu l’éon Hadéen, la création de la Lune, et l’astéroïde qui a tué les dinosaures », explique la fameuse troisième planète du Système solaire. « On pourrait croire que je suis habituée, mais j’en ai juste marre », poursuit-elle sans reconnaître la chance qu’elle a d’abriter la vie. « Vous pensez que le fait d’être l’hôte de millions d’espèces allait me rendre heureuse, mais je vous rappelle qu’il y a des pluies de diamants sur Neptune et Uranus pendant que moi j’ai un énorme trou dans ma couche d’ozone », précise la Terre pendant qu’un idiot lance une boîte de Nesquik dans l’océan depuis un paquebot carburant au pétrole brut.

La pollution n’est cependant pas la première chose à avoir fatigué la Terre : « De toute façon, je vous avoue que je commençais déjà à en avoir un peu marre depuis l’ère du Jurassique. »");
        $item1->setDate(new \DateTime("2018-01-04 16:01:25"));
        $item1->setUser($this->getReference('_reference_BlogBundleEntityUser1'));

        $manager->persist($item1);

    
        $manager->flush();
    }

}
