# src/BlogBundle/Resources/config/routing.yml

blog_home:
    path: /{page}
    defaults:
        page: 1
        _controller: BlogBundle:Blog:index
    requirements:
        page: \d*


blog_post:
    path: /post/{id}
    defaults:
        page: 1
        _controller: BlogBundle:Blog:post
    requirements:
        page: \d*