<?php

namespace CVBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use CVBundle\Entity\Competence;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadCVBundleEntityCompetence extends Fixture implements OrderedFixtureInterface, ContainerAwareInterface
{

    /**
     * @var ContainerInterface
     */
    private $container;
    public function setContainer(ContainerInterface $container = null) {
        $this->container = $container;
    }

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Competence::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $em = $this->container->get('doctrine')->getEntityManager();
        $em->getConnection()->exec('ALTER TABLE competence AUTO_INCREMENT = 1');

        $item1 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence1', $item1);
        $item1->setIntitule("Java SE");
        $item1->setImageName("java.png");
        $item1->setImagePath("/assets/database_files/competences/java.png");
        $item1->setImageSize(10456);

        $manager->persist($item1);

        $item2 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence2', $item2);
        $item2->setIntitule("Linux");
        $item2->setImageName("linux.png");
        $item2->setImagePath("/assets/database_files/competences/linux.png");
        $item2->setImageSize(20418);

        $manager->persist($item2);

        $item4 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence4', $item4);
        $item4->setIntitule("HTML & CSS");
        $item4->setImageName("html5-css3.png");
        $item4->setImagePath("/assets/database_files/competences/html5-css3.png");
        $item4->setImageSize(24847);

        $manager->persist($item4);

        $item5 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence5', $item5);
        $item5->setIntitule("Python");
        $item5->setImageName("python.png");
        $item5->setImagePath("/assets/database_files/competences/python.png");
        $item5->setImageSize(17803);

        $manager->persist($item5);

        $item12 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence12', $item12);
        $item12->setIntitule("PHP");
        $item12->setImageName("php.png");
        $item12->setImagePath("/assets/database_files/competences/php.png");
        $item12->setImageSize(5390);

        $manager->persist($item12);

        $item13 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence13', $item13);
        $item13->setIntitule("Javascript");
        $item13->setImageName("javascript_200x200.png");
        $item13->setImagePath("/assets/database_files/competences/javascript_200x200.png");
        $item13->setImageSize(11426);

        $manager->persist($item13);

        $item14 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence14', $item14);
        $item14->setIntitule("JQuery");
        $item14->setImageName("jQuery_200x200.png");
        $item14->setImagePath("/assets/database_files/competences/jQuery_200x200.png");
        $item14->setImageSize(7218);

        $manager->persist($item14);

        $item15 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence15', $item15);
        $item15->setIntitule("MySQL");
        $item15->setImageName("MySQL-Logo_200x200.png");
        $item15->setImagePath("/assets/database_files/competences/MySQL-Logo_200x200.png");
        $item15->setImageSize(7100);

        $manager->persist($item15);

        $item16 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence16', $item16);
        $item16->setIntitule("Oracle");
        $item16->setImageName("Oracle_200x200.png");
        $item16->setImagePath("/assets/database_files/competences/Oracle_200x200.png");
        $item16->setImageSize(8090);

        $manager->persist($item16);

        $item17 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence17', $item17);
        $item17->setIntitule("PostgreSQL");
        $item17->setImageName("postgresql_200x200.png");
        $item17->setImagePath("/assets/database_files/competences/postgresql_200x200.png");
        $item17->setImageSize(4776);

        $manager->persist($item17);

        $item18 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence18', $item18);
        $item18->setIntitule("C");
        $item18->setImageName("C_200x200.png");
        $item18->setImagePath("/assets/database_files/competences/C_200x200.png");
        $item18->setImageSize(17823);

        $manager->persist($item18);

        $item19 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence19', $item19);
        $item19->setIntitule("Bash");
        $item19->setImageName("Bash_200x200.png");
        $item19->setImagePath("/assets/database_files/competences/Bash_200x200.png");
        $item19->setImageSize(14595);

        $manager->persist($item19);

        $item20 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence20', $item20);
        $item20->setIntitule("Symfony");
        $item20->setImageName("symfony_200x200.png");
        $item20->setImagePath("/assets/database_files/competences/symfony_200x200.png");
        $item20->setImageSize(7087);

        $manager->persist($item20);

        $item21 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence21', $item21);
        $item21->setIntitule("Git");
        $item21->setImageName("Git_200x200.png");
        $item21->setImagePath("/assets/database_files/competences/Git_200x200.png");
        $item21->setImageSize(1271);

        $manager->persist($item21);

    
        $manager->flush();
    }

}
