<?php

namespace CVBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use CVBundle\Entity\Experience;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadCVBundleEntityExperience extends Fixture implements OrderedFixtureInterface, ContainerAwareInterface {

    /**
     * @var ContainerInterface
     */
    private $container;

    public function setContainer(ContainerInterface $container = null) {
        $this->container = $container;
    }

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder() {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager) {
        $manager->getClassMetadata(Experience::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $em = $this->container->get('doctrine')->getEntityManager();
        $em->getConnection()->exec('ALTER TABLE experience AUTO_INCREMENT = 1');


        $item2 = new Experience();
        $this->addReference('_reference_CVBundleEntityExperience2', $item2);
        $item2->setDateDebut(new \DateTime("2017-06-19 00:00:00"));
        $item2->setDateFin(new \DateTime("2017-09-15 00:00:00"));
        $item2->setVille("Mérignac");
        $item2->setIntitule("Stagiaire Développeur web");
        $item2->setEntreprise("SPIE ICS");
        $item2->setType("Stage");
        $item2->setDescription("Conception d'une plateforme d'e-commerce avec une partie client, et une partie administration.
Fonctionnalités :
- Génération d'un devis PDF à partir d'un panier validé sur le site
- Import d'un catalogue de produit Excel vers la base de données 
- Prix des produits personnalisé selon le client
- Gestion des entités de la plateforme depuis la partie Administration selon des rôles et des droits");
        $item2->setOrdre(1);
        $item2->setCodepostal(33);

        $manager->persist($item2);

        $item1 = new Experience();
        $this->addReference('_reference_CVBundleEntityExperience1', $item1);
        $item1->setDateDebut(new \DateTime("2016-07-01 00:00:00"));
        $item1->setDateFin(new \DateTime("2016-08-30 00:00:00"));
        $item1->setVille("Royan");
        $item1->setIntitule("Equipier Formation Cuisine");
        $item1->setEntreprise("Mc Donald's");
        $item1->setType("Job d'été");
        $item1->setDescription("- Préparation des sandwichs, Cuisson des produits
- Travail en équipe dans une production à la chaîne");
        $item1->setOrdre(2);
        $item1->setCodepostal(17);

        $manager->persist($item1);


        $manager->flush();
    }

}
