<?php

namespace CVBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use CVBundle\Entity\Formation;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadCVBundleEntityFormation extends Fixture implements OrderedFixtureInterface, ContainerAwareInterface {

    /**
     * @var ContainerInterface
     */
    private $container;

    public function setContainer(ContainerInterface $container = null) {
        $this->container = $container;
    }

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder() {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager) {
        $manager->getClassMetadata(Formation::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $em = $this->container->get('doctrine')->getEntityManager();
        $em->getConnection()->exec('ALTER TABLE formation AUTO_INCREMENT = 1');


        $item2 = new Formation();
        $this->addReference('_reference_CVBundleEntityFormation2', $item2);
        $item2->setAnneeDebut(new \DateTime("2015-09-04 00:00:00"));
        $item2->setAnneeFin(new \DateTime("2016-06-20 00:00:00"));
        $item2->setAnneeCourante("2ème");
        $item2->setIntitule("Licence Informatique");
        $item2->setEcole("Université de La Rochelle");
        $item2->setVille("La Rochelle");
        $item2->setCodepostal(17);
        $item2->setDescription("Cette 2ème année de Licence Informatique m'a permis de découvrir de nouvelles technologies, comme le C, le SQL, le  PHP ou encore JQuery. J'ai pu aussi beaucoup approfondir mes connaissances en java grâce à des cours de structures de données et de Programmation Orientée Objet.");
        $item2->setLien("https://formations.univ-larochelle.fr/licence-informatique");

        $manager->persist($item2);

        $item1 = new Formation();
        $this->addReference('_reference_CVBundleEntityFormation1', $item1);
        $item1->setAnneeDebut(new \DateTime("2014-09-04 00:00:00"));
        $item1->setAnneeFin(new \DateTime("2015-06-20 00:00:00"));
        $item1->setAnneeCourante("1ère");
        $item1->setIntitule("Licence Informatique");
        $item1->setEcole("Université de La Rochelle");
        $item1->setVille("La Rochelle");
        $item1->setCodepostal(17);
        $item1->setDescription("Cette première année de Licence est composée du 1er semestre commun à toutes les formations, chaque étudiant doit choisir des regroupements de matières en fonction de ses préférences. Le second semestre commence lui, à aborder vraiment tous les concepts de l'informatique. J'ai notamment pu voir lors de cette première année :
- Programmation Java
- Mathématiques pour l'informatique (Calcul matriciel, Mathématiques discrètes)
- HTML/CSS
- Architecture et Système");
        $item1->setLien("https://formations.univ-larochelle.fr/licence-informatique");

        $manager->persist($item1);


        $manager->flush();
    }

}
