<?php

namespace CVBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use CVBundle\Entity\Competence;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadCVBundleEntityCompetence extends Fixture implements OrderedFixtureInterface, ContainerAwareInterface {

    /**
     * @var ContainerInterface
     */
    private $container;

    public function setContainer(ContainerInterface $container = null) {
        $this->container = $container;
    }

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder() {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager) {
        $manager->getClassMetadata(Competence::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $em = $this->container->get('doctrine')->getEntityManager();
        $em->getConnection()->exec('ALTER TABLE competence AUTO_INCREMENT = 1');


        $item1 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence1', $item1);
        $item1->setIntitule("Java SE");
        $item1->setImage("assets/database_files/java.png");

        $manager->persist($item1);

        $item2 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence2', $item2);
        $item2->setIntitule("Linux");
        $item2->setImage("assets/database_files/linux.png");

        $manager->persist($item2);

        $item3 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence3', $item3);
        $item3->setIntitule("PHP");
        $item3->setImage("assets/database_files/php.png");

        $manager->persist($item3);

        $item4 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence4', $item4);
        $item4->setIntitule("HTML & CSS");
        $item4->setImage("assets/database_files/html5-css3.png");

        $manager->persist($item4);

        $item5 = new Competence();
        $this->addReference('_reference_CVBundleEntityCompetence5', $item5);
        $item5->setIntitule("Python");
        $item5->setImage("assets/database_files/python.png");

        $manager->persist($item5);


        $manager->flush();
    }

}
