<?php

namespace CVBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use CVBundle\Entity\Realisation;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadCVBundleEntityRealisation extends Fixture implements OrderedFixtureInterface, ContainerAwareInterface {

    /**
     * @var ContainerInterface
     */
    private $container;

    public function setContainer(ContainerInterface $container = null) {
        $this->container = $container;
    }

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder() {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager) {
        $manager->getClassMetadata(Realisation::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $em = $this->container->get('doctrine')->getEntityManager();
        $em->getConnection()->exec('ALTER TABLE realisation AUTO_INCREMENT = 1');

        $item1 = new Realisation();
        $this->addReference('_reference_CVBundleEntityRealisation1', $item1);
        $item1->setLink("https://github.com/guillaumehanotel");
        $item1->setTitre("Github");
        $item1->setDescription("Retrouvez mes travaux sur Github !");
        $item1->setImage("assets/database_files/github-logo.png");

        $manager->persist($item1);

        $item2 = new Realisation();
        $this->addReference('_reference_CVBundleEntityRealisation2', $item2);
        $item2->setLink("https://github.com/guillaumehanotel/Image-Enlarger");
        $item2->setTitre("Image Enlarger");
        $item2->setDescription("Programme Java qui multiplie la taille d'une image pixel par pixel");
        $item2->setImage("assets/database_files/enlarger.jpg");

        $manager->persist($item2);

        $item3 = new Realisation();
        $this->addReference('_reference_CVBundleEntityRealisation3', $item3);
        $item3->setLink("https://github.com/guillaumehanotel/FourmiLangton");
        $item3->setTitre("Fourmi de Langton");
        $item3->setDescription("Code Java illustrant le comportement de la fourmi de Langton");
        $item3->setImage("assets/database_files/langton_ant.png");

        $manager->persist($item3);


        $manager->flush();
    }

}
